<a href="https://colab.research.google.com/github/hiiya74/Sem-4-Python/blob/main/CH_6_classification_Analysis_Using_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# knn(k nearest neighbor)
import pandas as pd
df=pd.read_csv('knn.csv')
df

point  x1  x2  class
0     A   1   2      0
1     B   2   3      0
2     C   3   1      1
3     D   6   5      1

In [ ]:
df=df.drop('point',axis=1)
df

x1  x2  class
0   1   2      0
1   2   3      0
2   3   1      1
3   6   5      1

In [ ]:
y=df['class']
x=df.drop('class',axis=1)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
x_train

x1  x2
2   3   1
0   1   2
1   2   3

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
nn=KNeighborsClassifier(n_neighbors=3)
model=nn.fit(x_train,y_train)

In [ ]:
y_pred=model.predict(x_test)
y_pred

array([0])

In [ ]:
y_test

3    1
Name: class, dtype: int64

In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [ ]:
TN=cm[0][0]
FP=cm[0][1]
FN=cm[1][0]
TP=cm[1][1]
model_accuracy=(TP+TN)/(TP+TN+FP+FN)
model_accuracy

np.float64(0.0)

In [ ]:
# knn(k nearest neighbor)
import pandas as pd
df=pd.read_csv('diabetes.csv')
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [ ]:
y=df['Outcome']


In [ ]:
x=df.drop('Outcome',axis=1)


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
x_train

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
663            9      145             80             46      130  37.9   
712           10      129             62             36        0  41.2   
161            7      102             74             40      105  37.2   
509            8      120             78              0        0  25.0   
305            2      120             76             37      105  39.7   
..           ...      ...            ...            ...      ...   ...   
645            2      157             74             35      440  39.4   
715            7      187             50             33      392  33.9   
72            13      126             90              0        0  43.4   
235            4      171             72              0        0  43.6   
37             9      102             76             37        0  32.9   

     DiabetesPedigreeFunction  Age  
663                     0.637   40  
712                     0.441   38  
161                     0.204   45  
509                     0.409   64  
305                     0.215   29  
..                        ...  ...  
645                     0.134   30  
715                     0.826   34  
72                      0.583   42  
235                     0.479   26  
37                      0.665   46  

[614 rows x 8 columns]

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
nn=KNeighborsClassifier(n_neighbors=27)
model=nn.fit(x_train,y_train)

In [ ]:
y_pred=model.predict(x_test)
y_pred

array([1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
y_test

285    0
101    0
581    0
352    0
726    0
      ..
563    0
318    0
154    1
684    0
643    0
Name: Outcome, Length: 154, dtype: int64

In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

In [ ]:
TN=cm[0][0]
FP=cm[0][1]
FN=cm[1][0]
TP=cm[1][1]
model_accuracy=(TP+TN)/(TP+TN+FP+FN)
model_accuracy

np.float64(0.7402597402597403)

In [ ]:
error_rate=(FP+FN)/(TP+TN+FP+FN)
error_rate

In [ ]:
error_rate=1-model_accuracy
error_rate

In [ ]:
sensitivity=TP/(TP+FN)
sensitivity

In [ ]:
specificity=TN/(TN+FP)
specificity

In [ ]:
# DecionTreeClassifier

In [ ]:
import pandas as pd
df=pd.read_csv('diabetes.csv')
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [ ]:
y=df['Outcome']
x=df.drop('Outcome',axis=1)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(criterion='entropy',max_depth=12)

In [ ]:
model=dt.fit(x_train,y_train)

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[74, 25],
       [16, 39]])

In [ ]:
TN=cm[0][0]
FP=cm[0][1]
FN=cm[1][0]
TP=cm[1][1]
model_accuracy=(TP+TN)/(TP+TN+FP+FN)
model_accuracy

np.float64(0.7337662337662337)

In [ ]:
error_rate=1-model_accuracy
error_rate

np.float64(0.26623376623376627)

In [ ]:
error_rate=(FP+FN)/(TP+TN+FP+FN)
error_rate

np.float64(0.2662337662337662)

In [ ]:
sensitivity=TP/(TP+FN)#recall
sensitivity

np.float64(0.7090909090909091)

In [ ]:
specificity=TN/(TN+FP)
specificity

np.float64(0.7474747474747475)

In [ ]:
from sklearn import tree
gt=tree.export_text(dt)
print(gt)

|--- feature_1 <= 127.50
|   |--- feature_7 <= 28.50
|   |   |--- feature_5 <= 30.95
|   |   |   |--- feature_6 <= 0.67
|   |   |   |   |--- class: 0
|   |   |   |--- feature_6 >  0.67
|   |   |   |   |--- feature_6 <= 0.69
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- feature_6 >  0.69
|   |   |   |   |   |--- class: 0
|   |   |--- feature_5 >  30.95
|   |   |   |--- feature_2 <= 37.00
|   |   |   |   |--- class: 1
|   |   |   |--- feature_2 >  37.00
|   |   |   |   |--- feature_6 <= 0.50
|   |   |   |   |   |--- feature_3 <= 8.50
|   |   |   |   |   |   |--- feature_1 <= 109.50
|   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |   |--- feature_1 >  109.50
|   |   |   |   |   |   |   |--- feature_1 <= 123.00
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_1 >  123.00
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_3 >  8.50
|   |   |   |   |   |   |--- feature_5 <= 31.80
|   |   |   |   |   |   

In [ ]:
# QB-251The task involves building a Decision Tree classifier to predict whether to play tennis based on weather conditions.
# The dataset used for this task is the PlayTennis dataset, which contains information about various weather attributes such
# as outlook, temperature, humidity, and wind, along with the corresponding decision to play tennis or not. Use PlayTennis.csv
# for dataset.

import pandas as pd
df=pd.read_csv('PlayTennis.csv')
df

outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no

In [ ]:
y=df['play']
x=df.drop('play',axis=1)
x=pd.get_dummies(x,drop_first=True)
x

windy  outlook_rainy  outlook_sunny  temp_hot  temp_mild  humidity_normal
0   False          False           True      True      False            False
1    True          False           True      True      False            False
2   False          False          False      True      False            False
3   False           True          False     False       True            False
4   False           True          False     False      False             True
5    True           True          False     False      False             True
6    True          False          False     False      False             True
7   False          False           True     False       True            False
8   False          False           True     False      False             True
9   False           True          False     False       True             True
10   True          False           True     False       True             True
11   True          False          False     False       True            False
12  False          False          False      True      False             True
13   True           True          False     False       True            False

In [ ]:
from sklearn.metrics import classification_report
cr=classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.82      0.75      0.78        99
           1       0.61      0.71      0.66        55

    accuracy                           0.73       154
   macro avg       0.72      0.73      0.72       154
weighted avg       0.75      0.73      0.74       154



Write Python code to train a kNN classifier using the following steps:
• Split the dataset X into training and testing sets with a test size of 0.3 and a random state
of 42.
• Initialize a kNN classifier with 5 neighbors.
• Train the classifier on the training set.
• Make predictions on the test set.
• Calculate and print the accuracy score of the classifier.**bold text**

In [10]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_wine
# Load the Wine dataset
wine = load_wine()
X = wine.data
y = wine.target
# Split the dataset into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=42)
# Initialize a kNN classifier with 5 neighbors
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
# Train the classifier on the training set
knn.fit(X_train, y_train)
# Make predictions on the test set
y_pred = knn.predict(X_test)
# Calculate and print the accuracy score of the classifier
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy of kNN classifier: {accuracy:.2f}')

Accuracy of kNN classifier: 0.74


In [5]:
# kNN (k-Nearest Neighbors) with confusion matrix and metrics

import pandas as pd
# 1. Load dataset
df = pd.read_csv('knn.csv')  # Make sure this CSV exists in your path

# 2. Drop unnecessary column
df = df.drop('point', axis=1)

# 3. Separate features and target
y = df['class']
x = df.drop('class', axis=1)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x = scaler.fit_transform(x)

# 4. Train-test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

# 5. Train kNN model
from sklearn.neighbors import KNeighborsClassifier
nn = KNeighborsClassifier(n_neighbors=3)
model = nn.fit(x_train, y_train)

# 6. Make predictions
y_pred = model.predict(x_test)

# 7. Evaluate using confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Unpack confusion matrix
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]
TP = cm[1][1]

# 8. Metrics
model_accuracy = (TP + TN) / (TP + TN + FP + FN)
error_rate = 1 - model_accuracy
sensitivity = TP / (TP + FN)
specificity = TN / (TN + FP)

# 9. Print results
print(f"Accuracy      : {model_accuracy:.2f}")
print(f"Error Rate    : {error_rate:.2f}")
print(f"Sensitivity   : {sensitivity:.2f}")
print(f"Specificity   : {specificity:.2f}")


Confusion Matrix:
[[0 0]
 [1 0]]
Accuracy      : 0.00
Error Rate    : 1.00
Sensitivity   : 0.00
Specificity   : nan


<ipython-input-5-c7247747b42e>:47: RuntimeWarning: invalid value encountered in scalar divide
  specificity = TN / (TN + FP)
